[audio]
enable_sounds = true

[backdrop]
enabled = true

[bar]
order = [ "default" ]

    [bar.default]
    capsule = true
    center = [ "clock", "date" ]
    concave_edge_corners = false
    end = [
        "tray",
        "notifications",
        "clipboard",
        "network",
        "bluetooth",
        "volume",
        "input_volume",
        "brightness",
        "battery",
        "session"
    ]
    font_weight = 400
    margin_ends = 0
    radius = 0
    shadow = false
    start = [ "group:g1", "workspaces", "taskbar", "media" ]

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "control-center", "launcher", "settings", "wallpaper" ]
        opacity = 1.0
        padding = 6.0
        widget_spacing = 12

[battery]
warning_threshold = 20

[calendar]
enabled = true

    [calendar.account.personal_google]
    type = "google"

    [calendar.account.personal_icloud]
    provider = "icloud"
    type = "caldav"
    username = "andreagatto2004@gmail.com"

[control_center]
sidebar = "full"
sidebar_section = "full"

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
auto_hide = true
concave_edge_corners = false
cross_axis_padding = 4
icon_size = 32
item_spacing = 4
launcher_position = "start"
magnification_scale = 1.2500000037252903
main_axis_padding = 4
radius = 8
reserve_space = false

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = false
    timeout = 660.0

[location]
address = "Milan"

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 128.0
    box_width = 720.0
    cx = 768.0
    cy = 496.0
    output = "eDP-1"
    placement_height = 864.0
    placement_width = 1536.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = false
        show_session_buttons = true
        show_unlock_hint = false
        show_weather = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 0.0
    box_width = 0.0
    cx = 768.0
    cy = 176.0
    output = "eDP-1"
    placement_height = 864.0
    placement_width = 1536.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = true
        clock_style = "digital"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 0.0
    box_width = 0.0
    cx = 768.0
    cy = 646.0
    output = "eDP-1"
    placement_height = 864.0
    placement_width = 1536.0
    rotation = 0.0
    type = "media_player"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        hide_when_no_media = true
        layout = "horizontal"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 48.0
    box_width = 128.0
    cx = 768.0
    cy = 264.0
    output = "eDP-1"
    placement_height = 864.0
    placement_width = 1536.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        format = "{:%d/%m/%Y}"

[nightlight]
enabled = true

[plugins]
enabled = []

[shell]
app_icon_color = "on_surface_variant"
corner_radius_scale = 0.5000000074505806
font_family = "Noto Sans"
polkit_agent = true

    [shell.panel]
    clipboard_position = "auto"
    control_center_placement = "floating"
    session_placement = "floating"
    transparency_mode = "glass"
    wallpaper_placement = "floating"

    [shell.screenshot]
    directory = "/home/andrea/Pictures/Screenshots"

[theme]
builtin = "Ayu"
community_palette = "Jiva Paper"
custom_palette = "Artemis"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "kcolorscheme", "niri", "qt" ]
    community_ids = [ "fastfetch", "papirus-icons" ]

[wallpaper]
directory = "/home/andrea/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/andrea/Pictures/Wallpapers/wallhaven-6ly5lw.jpg"

    [wallpaper.last]
    path = "/home/andrea/Pictures/Wallpapers/wallhaven-6ly5lw.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/andrea/Pictures/Wallpapers/wallhaven-6ly5lw.jpg"

[widget.battery]
hide_when_full = true
hide_when_plugged = true

[widget.clock]
tooltip_format = "{:%H:%M:%S}"

[widget.control-center]
glyph = "niri"

[widget.date]
tooltip_format = "{:%d/%m/%Y}"

[widget.input_volume]
hide_when_inactive = true

[widget.launcher]
glyph = "search"

[widget.media]
hide_when_no_media = true

[widget.network]
show_label = false

[widget.tray]
detached_panel = true
drawer = true
pinned = [ "Fcitx" ]
