# Written by sub_transition on Wed Feb 25 16:28:06 2026.
menu_font_size=22
skip_non_dialogue=yes
skip_immediately=no
inter_speed=2
normal_speed=1
pause_on_start=no
pause_before_end=yes
hide_subs_when_playing=no
start_delay=0.1
reset_before=0.6
min_duration=0.4
start_enabled=no
notifications=no
